[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "video-status"
version = "0.1.0"
description = "FOSDEM video status"
requires-python = ""
dependencies = [
    "pyserial",
]

[project.scripts]
video-status = "cli.video_status:main"

[tool.setuptools]
packages = ["cli"]

[tool.setuptools.package-data]
src = ["*.py"]
